name: street-sign-classifier
dependencies:
  - python=3.6
  - jupyter=1.0.0
  - matplotlib=3.0.2
  - pandas=0.24.1
  - numpy=1.16.2
  - scikit-image=0.14.2
  - scikit-learn=0.20.3
  - keras=2.2.4
  - tensorflow=1.11.0
  - pandoc=2.2.3.2
