#! /bin/bash
set -e

function download_data_if_needed {
  if [[ ! -d data ]]; then
    ./download_data.py
  else
    min_expected_data_size_in_bytes=700000
    data_size_in_bytes=$(du -s data | cut -f1)
    if [[ $data_size_in_bytes -lt $min_expected_data_size_in_bytes ]]; then
      ./download_data.py
    fi
  fi
}

function create_or_update_conda_env {
  set +e

  # Try to create the virtual environment for the first time
  echo "Creating virtual environment..."
  create_res=$(conda env create -f environment.yml 2>&1)

  # If the virtual environment already exists, then update it
  if [[ $create_res == *"prefix already exists:"* ]]; then
    echo "Virtual environment already exists."
    echo "Updating virtual environment..."
    updates_res=$(conda env update -f environment.yml 2>&1)
    echo "Virtual environment updated."
  else
    echo "Virtual environment created."
  fi

  set -e
}

# (1) Figure out where `conda` is installed (Anaconda or Miniconda)
if [[ -d "/anaconda3" ]]; then
  CONDA_DIR="/anaconda3"
elif [[ -d "$HOME/anaconda3" ]]; then
  CONDA_DIR="$HOME/anaconda3"
elif [[ -d "$HOME/miniconda" ]]; then
  CONDA_DIR="$HOME/miniconda"
else
  echo "Could not find anaconda3 or miniconda installation."
  echo "Exiting."
  exit 1
fi

# (2) Get `conda` added to path so we can use it below
if [[ -f "$CONDA_DIR/etc/profile.d/conda.sh" ]]; then
  . "$CONDA_DIR/etc/profile.d/conda.sh"
else
  export PATH="$CONDA_DIR/bin:$PATH"
fi

download_data_if_needed

create_or_update_conda_env

echo "Activating virtual environment..."
conda activate street-sign-classifier

echo "Starting Jupyter notebook..."
jupyter notebook